server:
  port: 8081

spring:
  application:
    name: service-invoker

eureka:
  instance:
    #    配置该服务实例的主机名称
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/